language: julia
os:
  - osx
  - linux
julia:
  - 0.5
  - nightly
notifications:
  email: false
#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("ZStd"); Pkg.test("ZStd"; coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("ZStd")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
#  - julia -e 'cd(Pkg.dir("ZStd")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
